FROM python:3.8-slim
RUN mkdir /app
WORKDIR "/app"
RUN pip3 install --upgrade pip
COPY ./requirements.txt /app/requirements.txt
RUN pip3 install -r /app/requirements.txt
RUN pip3 install wheel
ENV PYTHONPATH=/app/src
ADD ./dist/pyamicreator-*-py2.py3-none-any.whl /app/libs/pyamicreator/pyamicreator-1.0.0-py2.py3-none-any.whl
RUN pip3 install /app/libs/pyamicreator/pyamicreator-1.0.0-py2.py3-none-any.whl
ENTRYPOINT [ "ami-creator" ]